import { confirmProjectReplacement } from "./browser-fixture.mjs";
import {transformMatrix,groupWorldTransform} from '../app/group-transforms.ts';
import {createRequire} from 'node:module';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE||'playwright');const browser=await chromium.launch({channel:'chrome',headless:true});
try{
 const page=await browser.newPage({viewport:{width:1800,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{window.showSaveFilePicker=undefined;window.showOpenFilePicker=undefined;});await page.goto('http://localhost:3000/');await page.getByText('Manual save only',{exact:true}).waitFor();await page.getByRole('button',{name:'3D',exact:true}).click();await page.getByRole('button',{name:'Load Demo Scene',exact:true}).click();await confirmProjectReplacement(page);
 const save=async()=>{await page.getByRole('button',{name:'File',exact:true}).click();const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Save As…',exact:true}).click();return JSON.parse(await fs.readFile(await(await pending).path(),'utf8'));};
 const importModel=async()=>{await page.getByRole('button',{name:'Import Model…',exact:true}).click();const d=page.getByRole('dialog');await d.locator('input[type=file]').first().setInputFiles({name:'structure.obj',mimeType:'text/plain',buffer:Buffer.from('o Left\nv -2 0 0\nv 0 0 0\nv -1 2 0\nf 1 2 3\no Right\nv 0 0 0\nv 2 0 0\nv 1 2 0\nf 4 5 6')});await d.getByRole('button',{name:'Read model',exact:true}).click();await d.getByLabel('Source units').selectOption('m');await d.getByRole('button',{name:'Import into scene',exact:true}).click();};
 await importModel();const before=await save(),model=before.simulation.models[0],root=model.nodes[0],left=model.nodes.find(n=>n.name==='Left');
 const tree=page.getByRole('tree',{name:'Imported models'});await tree.getByRole('button',{name:'Expand '+root.name,exact:true}).click();await tree.getByRole('button',{name:'Expand Group',exact:true}).click();
 await tree.getByRole('button',{name:'Left',exact:true}).dblclick();await page.getByRole('textbox',{name:'Item name',exact:true}).fill('Platform');await page.getByRole('textbox',{name:'Item name',exact:true}).press('Enter');assert.equal((await save()).simulation.models[0].nodes.find(n=>n.id===left.id).name,'Platform');
 await tree.getByRole('button',{name:'Platform',exact:true}).dblclick();await page.getByRole('textbox',{name:'Item name',exact:true}).fill('Discard');await page.getByRole('textbox',{name:'Item name',exact:true}).press('Escape');assert.equal(await tree.getByRole('button',{name:'Platform',exact:true}).count(),1);
 // Mixed selection creates one shared group and keeps existing model matrices.
 await page.getByRole('button',{name:'Select Center Wall',exact:true}).click();await tree.getByRole('button',{name:root.name,exact:true}).click({modifiers:['Control']});
 await page.locator('aside[class*="inspector"]').last().getByRole('button',{name:'Group',exact:true}).first().click();const grouped=await save(),group=grouped.simulation.groups.at(-1);assert.equal(group.sliceIds.length,1);assert.equal(grouped.simulation.models[0].nodes[0].sceneGroupId,group.id);assert.deepEqual(grouped.simulation.models[0].nodes.map(n=>n.matrix),model.nodes.map(n=>n.matrix));
 const groupRow=page.locator('.hierarchy-row.group').filter({has:page.locator('.hierarchy-name > span',{hasText:group.name})}).first();
 // Hierarchy reveal crosses shared groups for both imported parts and linked LED slices.
 const hierarchyContext=page.locator('.hierarchy-focus-context');
 await tree.getByRole('button',{name:'Platform',exact:true}).click();await groupRow.getByRole('button',{name:'Collapse group',exact:true}).click();
 assert(await groupRow.evaluate(e=>e.classList.contains('contains-selection')));assert.equal(await groupRow.getAttribute('aria-selected'),'false');
 await hierarchyContext.hover();await page.keyboard.press('s');await tree.getByRole('button',{name:'Platform',exact:true}).waitFor();assert.equal(await groupRow.getByRole('button',{name:'Collapse group',exact:true}).count(),1);
 await page.getByRole('button',{name:'Select Center Wall',exact:true}).click();await groupRow.getByRole('button',{name:'Collapse group',exact:true}).click();assert(await groupRow.evaluate(e=>e.classList.contains('contains-selection')));
 await hierarchyContext.getByRole('button',{name:'Focus',exact:true}).click();await page.getByRole('button',{name:'Select Center Wall',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Select Center Wall',exact:true}).locator('..').getAttribute('aria-selected'),'true');
 await groupRow.locator('.hierarchy-name').click();
 const x=page.getByRole('group',{name:'Position coordinates',exact:true}).locator('input').first();const oldX=Number(await x.inputValue());await x.fill(String(oldX+3));await x.press('Enter');const moved=await save();assert(Math.abs(moved.simulation.models[0].nodes.find(n=>n.id===left.id).matrix[12]-left.matrix[12]-3)<1e-6);assert(Math.abs(moved.simulation.groups.at(-1).transform.position[0]-group.transform.position[0]-3)<1e-6);
 await page.getByRole('button',{name:/Undo .*Set position/}).click();const undone=await save();assert.deepEqual(undone.simulation.models[0].nodes.find(n=>n.id===left.id).matrix,left.matrix);
 // Pivot edit does not move either kind of geometry.
 await groupRow.locator('.hierarchy-name').click();await page.getByRole('combobox',{name:'Pivot mode',exact:true}).selectOption('bottom-left');const pivoted=await save();assert.deepEqual(pivoted.simulation.models[0].nodes.find(n=>n.id===left.id).matrix,left.matrix);
 // Viewport drag must move both render layers and update coordinates before release.
 await page.getByRole('combobox',{name:'Pivot mode',exact:true}).selectOption('center');
 const view=page.getByRole('region',{name:'3D viewport',exact:true});await view.focus();await page.keyboard.press('F4');await page.keyboard.press('s');await page.keyboard.press('e');await page.waitForTimeout(150);
 const dragBefore=await save();await view.focus();
 const point=await view.locator('canvas').evaluate(canvas=>{const copy=document.createElement('canvas');copy.width=canvas.width;copy.height=canvas.height;const ctx=copy.getContext('2d');ctx.drawImage(canvas,0,0);const data=ctx.getImageData(0,0,copy.width,copy.height).data,pixels=[];for(let y=0;y<copy.height;y++)for(let x=Math.floor(copy.width/2);x<copy.width;x++){const i=(y*copy.width+x)*4;if(data[i]>220&&data[i+1]<40&&data[i+2]<40)pixels.push([x,y]);}const right=Math.max(...pixels.map(p=>p[0])),block=pixels.filter(p=>p[0]>right-10),r=canvas.getBoundingClientRect();return{x:r.x+(right-5)*r.width/copy.width,y:r.y+block.reduce((s,p)=>s+p[1],0)/block.length*r.height/copy.height};});
 const startX=Number(await x.inputValue());await page.mouse.move(point.x,point.y);await page.mouse.down();await page.mouse.move(point.x+45,point.y,{steps:12});await page.waitForTimeout(120);const liveX=Number(await x.inputValue());assert(Math.abs(liveX-startX)>.01,'Mixed group coordinates update while dragging');await page.mouse.up();
 const dragAfter=await save(),deltaX=dragAfter.simulation.groups.find(g=>g.id===group.id).transform.position[0]-dragBefore.simulation.groups.find(g=>g.id===group.id).transform.position[0];assert(Math.abs(deltaX)>.01);assert(Math.abs(dragAfter.simulation.models[0].nodes.find(n=>n.id===left.id).matrix[12]-dragBefore.simulation.models[0].nodes.find(n=>n.id===left.id).matrix[12]-deltaX)<1e-6);
 await page.getByRole('button',{name:/Undo .*Transform group selection/}).click();await groupRow.locator('.hierarchy-name').click();
 // Move an LED slice directly into an imported group: promote its ancestor chain.
 await page.getByRole('button',{name:'Select Header Ribbon',exact:true}).dragTo(tree.getByRole('button',{name:'Group',exact:true}));const promoted=await save();const importedGroup=model.nodes.find(n=>n.name==='Group');assert(promoted.simulation.groups.some(g=>g.id===importedGroup.id&&g.sliceIds.length===1));assert(promoted.simulation.models.some(m=>m.nodes[0].id===left.id&&m.nodes[0].sceneGroupId===importedGroup.id));
 // Reparent a model part to the outer mixed group.
 await page.getByRole('button',{name:'Platform',exact:true}).dragTo(groupRow.locator('.hierarchy-name'));const reparented=await save();assert.equal(reparented.simulation.models.find(m=>m.nodes[0].id===left.id).nodes[0].sceneGroupId,group.id);assert.deepEqual(reparented.simulation.models.find(m=>m.nodes[0].id===left.id).nodes[0].matrix,left.matrix);
 // Saved links and geometry survive a project reopen.
 await page.getByRole('button',{name:'File',exact:true}).click();const chooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Open Project…',exact:true}).click();await(await chooser).setFiles({name:'mixed.lo2s',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(reparented))});await page.waitForTimeout(250);const restored=await save();assert.deepEqual(restored.simulation.models,reparented.simulation.models);assert.deepEqual(restored.simulation.groups,reparented.simulation.groups);
 // Parent locks protect imported descendants, including keyboard deletion.
 await groupRow.getByRole('button',{name:'Lock group',exact:true}).click();await page.getByRole('button',{name:'Platform',exact:true}).click();assert(await x.isDisabled());await page.keyboard.press('Delete');assert.equal((await save()).simulation.models.length,reparented.simulation.models.length);await groupRow.getByRole('button',{name:'Unlock group',exact:true}).click();
 await page.getByRole('button',{name:'Export',exact:true}).click();const exportPending=page.waitForEvent('download');await page.getByRole('button',{name:'GLB \u00b7 Universal binary',exact:true}).click();const bytes=await fs.readFile(await(await exportPending).path());const glb=JSON.parse(bytes.subarray(20,20+bytes.readUInt32LE(12)).toString());const shared=glb.nodes.find(n=>n.extras?.groupId===group.id);assert(shared,'Shared group is exported');assert(shared.children.some(i=>glb.nodes[i].name==='Platform'),'Imported part retains its shared group parent in GLB');
 const home=page.locator('.hierarchy-screen').filter({has:page.locator('.hierarchy-row.screen strong',{hasText:'Stage - Main'})}),other=page.locator('.hierarchy-screen').filter({has:page.locator('.hierarchy-row.screen strong',{hasText:'Slices'})});
 await page.getByRole('button',{name:'Platform',exact:true}).dragTo(home.locator('.hierarchy-row.screen'));assert.equal((await save()).simulation.models.find(m=>m.nodes[0].id===left.id).nodes[0].sceneGroupId,group.id,'Models cannot enter screen containers');
 await groupRow.dragTo(home.locator('.hierarchy-row.screen'));assert.equal((await save()).simulation.groups.find(g=>g.id===group.id).parentId,null,'Groups cannot enter screen containers');
 await page.getByRole('button',{name:'Select Center Wall',exact:true}).dragTo(other.locator('.hierarchy-row.screen'));assert((await save()).simulation.groups.find(g=>g.id===group.id).sliceIds.length,'Slices cannot move to another source screen');
 await page.getByRole('button',{name:'Select Center Wall',exact:true}).dragTo(home.locator('.hierarchy-row.screen'));assert.equal((await save()).simulation.groups.find(g=>g.id===group.id).sliceIds.length,0);assert.equal(await home.getByRole('button',{name:'Select Center Wall',exact:true}).count(),1);await page.getByRole('button',{name:/Undo .*Return slice to original screen/}).click();
 await groupRow.locator('.hierarchy-name').click();await page.screenshot({path:'work/v080-local/mixed-hierarchy.png'});
 await view.focus();await page.keyboard.press('Delete');const deleted=await save();assert.equal(deleted.simulation.models.length,0,'Delete mixed group removes imported descendants');assert.equal(deleted.rawXml,restored.rawXml,'Delete never changes Resolume slices');assert.equal(deleted.simulation.groups.length,0,'Selected group branch is removed');for(const id of reparented.simulation.groups.flatMap(g=>g.sliceIds)){const owner=reparented.simulation.groups.find(g=>g.sliceIds.includes(id)),world=transformMatrix(groupWorldTransform(owner.id,reparented.simulation.groups)).multiply(transformMatrix(reparented.simulation.transforms[id]));const result=transformMatrix(deleted.simulation.transforms[id]);world.elements.forEach((v,i)=>assert(Math.abs(v-result.elements[i])<1e-6));}assert.equal(await page.locator('.hierarchy-screen').getByRole('button',{name:'Select Center Wall',exact:true}).count(),1);
 await page.getByRole('button',{name:/Undo .*Remove selected groups/}).click();assert.equal((await save()).simulation.models.length,restored.simulation.models.length);
 await view.focus();await page.keyboard.press('Control+a');await page.keyboard.press('Control+g');
 assert.equal(await page.locator('.hierarchy-screen').count(),2,'Source screens remain visible when every slice is grouped');assert.equal(await page.locator('.hierarchy-screen .hierarchy-row.child').count(),0);
 await page.locator('aside[class*="inspector"]').last().getByRole('button',{name:'Ungroup',exact:true}).click();assert.equal(await page.locator('.hierarchy-screen .hierarchy-row.child').count(),7,'Ungroup returns every direct slice to its source screen');
 assert.deepEqual(errors,[]);console.log('Mixed grouping, model rename/escape, parenting in both directions, coordinates, pivots, Undo and project round-trip passed.');
}finally{await browser.close();}
