import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const { chromium } = createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1500, height: 1000 } });
await page.addInitScript(() => { window.showSaveFilePicker = undefined; });
const errors=[]; page.on('pageerror',e=>errors.push(e.message)); page.on('console',m=>{if(m.type()==='error')console.log('browser:',m.text());});
try {
  await page.goto(process.env.OPTICMESH_URL || 'http://localhost:3000/');
  await page.getByText('Manual save only',{exact:true}).waitFor();
  await page.getByRole('button',{name:'3D',exact:true}).click();
  await page.getByRole('button',{name:'Import Model…',exact:true}).click();
  const dialog=page.getByRole('dialog');
  await dialog.locator('input[type=file]').first().setInputFiles({name:'stage.obj',mimeType:'text/plain',buffer:Buffer.from('o Platform\nv -1 0 -1\nv 1 0 -1\nv 1 0 1\nv -1 0 1\nf 1 2 3 4\no Tower\nv 0 0 0\nv 0 3 0\nv 1 0 0\nf 5 6 7\n')});
  await dialog.getByRole('button',{name:'Read model',exact:true}).click();
  await dialog.getByRole('button',{name:'Import into scene',exact:true}).waitFor();
  await dialog.locator('.model-preview').waitFor();
  assert(await dialog.getByRole('button',{name:'Import into scene',exact:true}).isDisabled(),'OBJ requires an explicit unit choice');
  await dialog.getByRole('combobox',{name:'Source units',exact:true}).selectOption('m');
  const error=await dialog.locator('[role=alert]').count() ? await dialog.locator('[role=alert]').textContent() : null; if(error)throw new Error(error);
  await dialog.getByRole('button',{name:'Import into scene',exact:true}).click();
  await page.getByRole('tree',{name:'Imported models'}).waitFor();
  assert(await page.locator('.hierarchy-tree').getByRole('tree',{name:'Imported models'}).count(),'Model is inside the scene tree');
  await page.getByRole('button',{name:'Material',exact:true}).click();
  const panel=page.getByLabel('Model material controls',{exact:true});
  const diffuse=panel.getByRole('slider',{name:'Diffuse intensity',exact:true});
  const picker=panel.getByLabel('Diffuse colour',{exact:true});
  const initialColor=await picker.inputValue();
  await picker.focus();
  await picker.evaluate(el=>{for(let i=0;i<100;i++){Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,'#'+(0x330000+i*100).toString(16).padStart(6,'0'));el.dispatchEvent(new Event('input',{bubbles:true}));}});
  await picker.blur();await page.waitForTimeout(80);
  assert.equal(await picker.inputValue(),'#3326ac','last colour survives coalesced preview and blur');
  await page.getByRole('button',{name:/^Undo/}).click();await page.getByRole('tree',{name:'Imported models'}).locator('.model-name').first().click();
  assert.equal(await picker.inputValue(),initialColor,'one Undo restores colour before the entire picker gesture');
  await panel.getByLabel('Diffuse colour',{exact:true}).fill('#dd5522');
  await panel.getByRole('slider',{name:'Metallic',exact:true}).focus();await page.keyboard.press('End');
  await panel.getByRole('slider',{name:'Roughness',exact:true}).focus();await page.keyboard.press('Home');await page.keyboard.press('ArrowRight');
  await panel.getByRole('slider',{name:'Specular',exact:true}).focus();await page.keyboard.press('Home');
  assert.equal(await panel.getByLabel('Material inheritance').inputValue(),'custom');
  const original=await diffuse.inputValue();const box=await diffuse.boundingBox();
  await page.mouse.move(box.x+box.width*.9,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width*.4,box.y+box.height/2,{steps:5});await page.mouse.up();
  assert.notEqual(await diffuse.inputValue(),original);
  await page.getByRole('button',{name:/^Undo/}).click();await page.getByRole('tree',{name:'Imported models'}).locator('.model-name').first().click();assert.equal(await diffuse.inputValue(),original,'one Undo reverses full slider drag');
  await panel.getByRole('slider',{name:'Roughness',exact:true}).dblclick();assert.equal(await panel.getByRole('slider',{name:'Roughness',exact:true}).inputValue(),'82');
  await panel.getByRole('slider',{name:'Metallic',exact:true}).focus();await page.keyboard.press('Home');
  await page.screenshot({path:'work/v080-local/material-panel.png'});
  const bounds=await panel.boundingBox();const body=await page.evaluate(()=>({w:innerWidth,scroll:document.documentElement.scrollWidth}));assert(bounds.x+bounds.width<=body.w);assert(body.scroll<=body.w);
  await page.getByRole('button',{name:'File',exact:true}).click();const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Save As…',exact:true}).click();const dl=await pending;const bytes=await fs.readFile(await dl.path());const project=JSON.parse(bytes);const material=project.simulation.models[0].nodes[0].material;
  assert.deepEqual(material,{color:'#dd5522',diffuse:1,metallic:0,roughness:.82,specular:0});
  await page.getByRole('button',{name:'Export',exact:true}).click();const exp=page.waitForEvent('download');await page.getByRole('button',{name:'GLB · Universal binary',exact:true}).click();const glb=await fs.readFile(await (await exp).path());const json=JSON.parse(glb.subarray(20,20+glb.readUInt32LE(12)).toString());assert(json.materials.some(m=>m.name.startsWith('Stage_dd5522')&&m.pbrMetallicRoughness.roughnessFactor===.82));
  await page.locator('input[accept*=".lo2s"]').first().setInputFiles({name:'materials.lo2s',mimeType:'application/json',buffer:bytes});await page.getByRole('tree',{name:'Imported models'}).locator('.model-name').first().click();assert.equal(await panel.getByLabel('Diffuse colour',{exact:true}).inputValue(),'#dd5522');
  for(const width of [1100,2560]){await page.setViewportSize({width,height:1000});await page.waitForTimeout(80);const bounded=await panel.evaluate(el=>{const r=el.getBoundingClientRect();return r.right<=innerWidth&&document.documentElement.scrollWidth<=innerWidth;});assert(bounded,'Material panel stays within workspace');}
  await page.setViewportSize({width:1500,height:1000});
  await panel.getByLabel('Model display').selectOption('wireframe');
  for(const label of ['Metallic','Roughness','Specular'])assert(await panel.getByRole('slider',{name:label,exact:true}).isDisabled());
  assert(await picker.isEnabled());assert(await diffuse.isEnabled());
  await picker.fill('#22bbff');await picker.blur();await page.waitForTimeout(100);assert.equal(await picker.inputValue(),'#22bbff');
  const linePixels=await page.getByRole('region',{name:'3D viewport',exact:true}).locator('canvas').evaluate(canvas=>{const c=document.createElement('canvas');c.width=canvas.width;c.height=canvas.height;const ctx=c.getContext('2d');ctx.drawImage(canvas,0,0);const data=ctx.getImageData(0,0,c.width,c.height).data;let count=0;for(let i=0;i<data.length;i+=4)if(data[i+1]>100&&data[i+2]>150&&data[i+2]>data[i]+50)count++;return count;});assert(linePixels>30,'Wireframe shows the chosen diffuse line colour');
  await panel.getByLabel('Model display').selectOption('shaded');assert(await panel.getByRole('slider',{name:'Metallic',exact:true}).isEnabled());assert.equal(await panel.getByRole('slider',{name:'Roughness',exact:true}).inputValue(),'82');
  await page.getByRole('tree',{name:'Imported models'}).getByRole('button',{name:/Toggle lock/}).first().click();assert(await diffuse.isDisabled());
  await page.getByRole('button',{name:'Patterns',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Material',exact:true}).count(),0);assert.equal(await page.getByLabel('Model material controls',{exact:true}).count(),0);
  await page.getByRole('button',{name:'3D',exact:true}).click();await page.getByRole('button',{name:'Material',exact:true}).click();
  const mixed=structuredClone(project),parts=mixed.simulation.models[0].nodes.filter(n=>n.geometry);parts[0].material={...material,roughness:.2};parts[1].material={...material,roughness:.8};
  await page.locator('input[accept*=".lo2s"]').first().setInputFiles({name:'mixed.lo2s',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(mixed))});
  const tree=page.getByRole('tree',{name:'Imported models'});
  for(let i=0;i<5;i++){const expand=tree.locator('.hierarchy-disclosure[aria-expanded="false"]').first();if(!await expand.count())break;await expand.click();}
  await tree.locator('.model-name').filter({hasText:'Platform'}).click();await tree.locator('.model-name').filter({hasText:'Tower'}).click({modifiers:['Control']});
  assert.equal(await panel.getByRole('slider',{name:'Roughness',exact:true}).getAttribute('aria-valuetext'),'Multiple values');
  await panel.getByRole('slider',{name:'Roughness',exact:true}).focus();await page.keyboard.press('End');assert.equal(await panel.getByRole('slider',{name:'Roughness',exact:true}).inputValue(),'100');
  await panel.getByLabel('Material inheritance').selectOption('inherit');assert.equal(await panel.getByRole('slider',{name:'Roughness',exact:true}).inputValue(),'82');
  assert.equal(errors.length,0,errors.join('\n'));
  console.log('Material tab, controls, drag Undo, double-click reset, lock, export and save/reopen passed.');
} finally {await browser.close();}
