import { confirmProjectReplacement } from "./browser-fixture.mjs";
import {createRequire} from 'node:module';import fs from 'node:fs/promises';import assert from 'node:assert/strict';import {transformMatrix} from '../app/group-transforms.ts';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE);const browser=await chromium.launch({channel:'chrome',headless:true});
try {
 const page=await browser.newPage({viewport:{width:1600,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>window.showSaveFilePicker=undefined);await page.goto('http://localhost:3000/');await page.getByText('Manual save only',{exact:true}).waitFor();await page.getByRole('button',{name:'3D',exact:true}).click();
 const view=page.getByRole('region',{name:'3D viewport',exact:true}),pivot=page.getByRole('combobox',{name:'Pivot mode',exact:true});assert(await pivot.isDisabled());
 const save=async()=>{await page.getByRole('button',{name:'File',exact:true}).click();const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Save As…',exact:true}).click();return JSON.parse(await fs.readFile(await (await pending).path(),'utf8'));};
 await page.getByRole('button',{name:'Load Demo Scene',exact:true}).click();await confirmProjectReplacement(page);await view.focus();await page.keyboard.press('Control+a');await page.keyboard.press('Control+g');assert(await pivot.isEnabled());const original=await save();
 await pivot.selectOption('top-left');assert.equal(await pivot.inputValue(),'top-left');const changed=await save();const g0=original.simulation.groups[0],g1=changed.simulation.groups[0];assert.notDeepEqual(g0.transform.position,g1.transform.position);
 for(const id of g0.sliceIds){const a=transformMatrix(g0.transform).multiply(transformMatrix(original.simulation.transforms[id])),b=transformMatrix(g1.transform).multiply(transformMatrix(changed.simulation.transforms[id]));a.elements.forEach((v,i)=>assert(Math.abs(v-b.elements[i])<1e-7));}
 console.log('Screen group pivot is editable; all child world matrices preserved.');
 await page.getByRole('group',{name:'XY pivot pad',exact:true}).press('Home');assert.equal(await pivot.inputValue(),'center');
 await page.getByRole('button',{name:'Import Model…',exact:true}).click();const d=page.getByRole('dialog');await d.locator('input[type=file]').first().setInputFiles({name:'pivot-stage.obj',mimeType:'text/plain',buffer:Buffer.from('o Left\nv 0 0 0\nv 200 0 0\nv 200 400 0\nv 0 400 0\nf 1 2 3 4')});await d.getByRole('button',{name:'Read model',exact:true}).click();await d.getByLabel('Source units').selectOption('cm');await d.getByRole('button',{name:'Import into scene',exact:true}).click();assert(await pivot.isEnabled());
 const modelBefore=(await save()).simulation.models[0];await pivot.selectOption('bottom-left');assert.equal(await pivot.inputValue(),'bottom-left');const modelAfter=(await save()).simulation.models[0];assert.deepEqual(modelAfter.nodes.map(n=>n.matrix),modelBefore.nodes.map(n=>n.matrix));assert.deepEqual(modelAfter.nodes[0].pivot,[0,0,0]);
 const xyz=page.locator('[class*="pivotCoordinates"] input');assert.equal(Number(await xyz.nth(0).inputValue()),-1);assert.equal(Number(await xyz.nth(1).inputValue()),-2);
 await xyz.nth(2).fill('1');await xyz.nth(2).press('Enter');assert.equal(await pivot.inputValue(),'custom');const saved=await save();assert.deepEqual(saved.simulation.models[0].nodes[0].pivot,[0,0,1]);
 // Numeric rotation uses the selected pivot too: a bottom-left point remains fixed.
 await pivot.selectOption('bottom-left');const rz=page.getByRole('group',{name:'Rotation coordinates',exact:true}).locator('input').nth(2);await rz.fill('90');await rz.press('Enter');const rotated=(await save()).simulation.models[0];assert(Math.abs(rotated.nodes.find(n=>n.geometry).matrix[12])<1e-7);assert(Math.abs(rotated.nodes.find(n=>n.geometry).matrix[13])<1e-7);
 await page.locator('input[accept*=".lo2s"]').first().setInputFiles({name:'pivots.lo2s',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(saved))});await page.getByRole('tree',{name:'Imported models'}).locator('.model-name').first().click();assert.equal(await pivot.inputValue(),'custom');await page.waitForTimeout(100);assert.equal(Number(await xyz.nth(2).inputValue()),1);
 await page.getByRole('tree',{name:'Imported models'}).getByRole('button',{name:/Toggle lock/}).first().click();assert(await pivot.isDisabled());
 assert.deepEqual(errors,[]);await page.screenshot({path:'work/v080-local/pivots-ui.png'});console.log('Model pivot presets, XY pad, metre offsets, custom Z, numeric rotation, save/reopen and locks passed.');
}finally{await browser.close();}
