import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {zipSync,strToU8} from 'three/examples/jsm/libs/fflate.module.js';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE||'playwright');
const vertices=Buffer.from(new Float32Array([0,0,0,2,0,0,0,3,0]).buffer);
const json={asset:{version:'2.0'},scene:0,scenes:[{nodes:[0]}],nodes:[{name:'Assembly',translation:[1,0,0],children:[1]},{name:'Panel',mesh:0}],meshes:[{primitives:[{attributes:{POSITION:0}}]}],buffers:[{byteLength:36,uri:'data:application/octet-stream;base64,'+vertices.toString('base64')}],bufferViews:[{buffer:0,byteOffset:0,byteLength:36}],accessors:[{bufferView:0,componentType:5126,count:3,type:'VEC3',min:[0,0,0],max:[2,3,0]}]};
const binaryJson=structuredClone(json);delete binaryJson.buffers[0].uri;
const text=Buffer.from(JSON.stringify(binaryJson)),padded=Buffer.alloc(Math.ceil(text.length/4)*4,32);text.copy(padded);
const glb=Buffer.alloc(12+8+padded.length+8+vertices.length);glb.writeUInt32LE(0x46546c67,0);glb.writeUInt32LE(2,4);glb.writeUInt32LE(glb.length,8);glb.writeUInt32LE(padded.length,12);glb.writeUInt32LE(0x4e4f534a,16);padded.copy(glb,20);const offset=20+padded.length;glb.writeUInt32LE(vertices.length,offset);glb.writeUInt32LE(0x004e4942,offset+4);vertices.copy(glb,offset+8);
const stl=`solid part\nfacet normal 0 0 1\nouter loop\nvertex 0 0 0\nvertex 2 0 0\nvertex 0 3 0\nendloop\nendfacet\nendsolid part\n`;
const usda=`#usda 1.0\n(\n defaultPrim = "Stage"\n metersPerUnit = 1\n upAxis = "Y"\n)\ndef Xform "Stage"\n{\n def Mesh "Panel"\n {\n  int[] faceVertexCounts = [3]\n  int[] faceVertexIndices = [0,1,2]\n  point3f[] points = [(0,0,0),(2,0,0),(0,3,0)]\n }\n}\n`;
const dae=`<?xml version="1.0"?><COLLADA xmlns="http://www.collada.org/2005/11/COLLADASchema" version="1.4.1"><asset><unit name="meter" meter="1"/><up_axis>Y_UP</up_axis></asset><library_geometries><geometry id="g"><mesh><source id="p"><float_array id="pa" count="9">0 0 0 2 0 0 0 3 0</float_array><technique_common><accessor source="#pa" count="3" stride="3"><param name="X" type="float"/><param name="Y" type="float"/><param name="Z" type="float"/></accessor></technique_common></source><vertices id="v"><input semantic="POSITION" source="#p"/></vertices><triangles count="1"><input semantic="VERTEX" source="#v" offset="0"/><p>0 1 2</p></triangles></mesh></geometry></library_geometries><library_visual_scenes><visual_scene id="Scene"><node id="Assembly" name="Assembly"><translate>1 0 0</translate><node id="Panel" name="Panel"><instance_geometry url="#g"/></node></node></visual_scene></library_visual_scenes><scene><instance_visual_scene url="#Scene"/></scene></COLLADA>`;
const gdtfXml=`<GDTF DataVersion="1.2"><FixtureType Name="Fixture"><Models><Model Name="Body" Length="1" Width="1" Height="1" PrimitiveType="Cube"/></Models><Geometries><Geometry Name="Base" Model="Body" Position="{1,0,0,0}{0,1,0,0}{0,0,1,0}{0,0,2,1}"/></Geometries></FixtureType></GDTF>`;
const gdtf=zipSync({'description.xml':strToU8(gdtfXml)});
const mvr=minor=>zipSync({'GeneralSceneDescription.xml':strToU8(`<GeneralSceneDescription verMajor="1" verMinor="${minor}"><Scene><AUXData/><Layers><Layer name="Stage"><ChildList><GroupObject name="Assembly"><Matrix>{1,0,0}{0,1,0}{0,0,1}{1000,2000,0}</Matrix><ChildList><SceneObject name="Panel"><Geometries><Geometry3D fileName="mesh.glb"/></Geometries></SceneObject><Fixture name="Fixture"><GDTFSpec>fixture.gdtf</GDTFSpec></Fixture></ChildList></GroupObject></ChildList></Layer></Layers></Scene></GeneralSceneDescription>`),'mesh.glb':glb,'fixture.gdtf':gdtf});
const chunk=(id,...parts)=>{const b=Buffer.concat([Buffer.alloc(6),...parts]);b.writeUInt16LE(id);b.writeUInt32LE(b.length,2);return b;};const count=Buffer.alloc(2);count.writeUInt16LE(3);const faces=Buffer.alloc(10);faces.writeUInt16LE(1);faces.writeUInt16LE(0,2);faces.writeUInt16LE(1,4);faces.writeUInt16LE(2,6);
const tds=chunk(0x4d4d,chunk(0x3d3d,chunk(0x4000,Buffer.from('Panel\0'),chunk(0x4100,chunk(0x4110,count,vertices),chunk(0x4120,faces)))));
const legacyMvr=(major=1,minor=4)=>zipSync({'GeneralSceneDescription.xml':strToU8(`<GeneralSceneDescription verMajor="${major}" verMinor="${minor}"><Scene><Layers><Layer name="Legacy stage"><ChildList><Truss name="Instance"><Matrix>{1,0,0}{0,1,0}{0,0,1}{1000,2000,3000}</Matrix><Geometries><Symbol symdef="part"/></Geometries></Truss><Fixture name="Fixture"><GDTFSpec>fixture.gdtf</GDTFSpec></Fixture></ChildList></Layer></Layers><AUXData><Symdef uuid="part"><ChildList><Geometry3D fileName="mesh.3ds"><Matrix>{1,0,0}{0,1,0}{0,0,1}{10,20,30}</Matrix></Geometry3D></ChildList></Symdef></AUXData></Scene></GeneralSceneDescription>`),'mesh.3ds':tds,'fixture.gdtf':gdtf});
const fixtures=[['mesh.gltf',Buffer.from(JSON.stringify(json))],['mesh.glb',glb],['mesh.3ds',tds],['mesh.stl',Buffer.from(stl)],['mesh.dae',Buffer.from(dae)],['mesh.usda',Buffer.from(usda)],['mesh.usd',Buffer.from(usda)],['mesh.usdz',zipSync({'mesh.usda':strToU8(usda)})],['fixture.gdtf',gdtf],['stage14.mvr',legacyMvr()],['stage15.mvr',mvr(5)],['stage16.mvr',mvr(6)]];
fixtures.push(['repair-attributes.obj',Buffer.from('o Platform\nv 0 0 0\nv 2 0 0\nv 0 3 0\nvt NaN 0\nvt 1 0\nvt 0 1\nvn NaN 0 1\nf 1/1/1 2/2/1 3/3/1')]);
fixtures.push(['unsupported13.mvr',legacyMvr(1,3)],['unsupported20.mvr',legacyMvr(2,0)]);
for (const name of ['exampleWindow.fbx','test.usdc']) {try{fixtures.push([name,await fs.readFile('work/model-import/'+name)]);}catch{}}
const browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage();
try{
 await page.goto('http://localhost:3000/');await page.getByText('Manual save only',{exact:true}).waitFor();
 for(const [name,data] of fixtures){
  const result=await page.evaluate(({name,bytes})=>new Promise(resolve=>{const worker=new Worker('/app/model-import.worker.ts?worker_file&type=module',{type:'module'});const timer=setTimeout(()=>{worker.terminate();resolve({error:'Worker timed out'});},20000);worker.onerror=e=>{clearTimeout(timer);worker.terminate();resolve({error:e.message});};worker.onmessage=e=>{if(e.data.model||e.data.error){clearTimeout(timer);worker.terminate();resolve(e.data);}};worker.postMessage({name,files:[{name,bytes:new Uint8Array(bytes).buffer}]});}),{name,bytes:[...data]});
  if(name.startsWith('unsupported')){assert.match(result.error,/MVR version (1\.3|2\.0) is unsupported/);console.log(name+': rejected with detected version');continue;}
  if(name==='stage14.mvr'){const mesh=result.model.nodes.find(n=>n.geometry);assert.deepEqual(mesh.matrix.slice(12,15),[1010,2020,3030],'Legacy 3DS symbol placement is retained');assert(result.model.nodes.some(n=>n.name==='Instance'));}
  assert(!result.error,`${name}: ${result.error}`);assert(result.model.triangles>0,name);assert(result.model.nodes.some(n=>n.geometry),name);
  if(name==='repair-attributes.obj'){assert(result.model.warnings.some(w=>w.includes('normals')));assert(result.model.warnings.some(w=>w.includes('UV')));assert.equal(result.model.triangles,1);}
  if(name.endsWith('.mvr')){assert.equal(result.model.triangles,1,'MVR retains the scene mesh without expanding GDTF fixtures');assert(!result.model.nodes.some(n=>n.name==='Fixture'),'Empty fixture metadata is omitted');}
  console.log(`${name}: ${result.model.triangles} triangles, ${result.model.nodes.length} nodes`);
 }
}finally{await browser.close();}
