import {createRequire} from 'node:module';import assert from 'node:assert/strict';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE||'playwright');const browser=await chromium.launch({channel:'chrome',headless:true});
try{for(const dpr of [1,2]){
 const page=await browser.newPage({viewport:{width:1600,height:1000},deviceScaleFactor:dpr}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://localhost:3000/');await page.getByText('Manual save only',{exact:true}).waitFor();await page.getByRole('button',{name:'3D',exact:true}).click();
 await page.getByRole('button',{name:'Import Model\u2026',exact:true}).click();const d=page.getByRole('dialog');
 const obj=Array.from({length:400},(_,i)=>{const x=i%20/10-1,y=Math.floor(i/20)/10+1,k=i*4+1;return `o Tile_${i}\nv ${x} ${y} 0\nv ${x+.1} ${y} 0\nv ${x+.1} ${y+.1} 0\nv ${x} ${y+.1} 0\nf ${k} ${k+1} ${k+2} ${k+3}`;}).join('\n');
 await d.locator('input[type=file]').first().setInputFiles({name:'dense-grid.obj',mimeType:'text/plain',buffer:Buffer.from(obj)});await d.getByRole('button',{name:'Read model',exact:true}).click();await d.getByLabel('Source units').selectOption('m');await d.getByRole('button',{name:'Import into scene',exact:true}).click();
 const view=page.getByRole('region',{name:'3D viewport',exact:true}),canvas=view.locator('canvas'),root=page.getByRole('tree',{name:'Imported models'}).locator('.model-name').first();
 await view.focus();await view.hover();await page.keyboard.press('F4');await page.keyboard.press('f');const bounds=await view.locator('[aria-label="Front viewport"]').boundingBox();await page.mouse.click(bounds.x+10,bounds.y+10);await page.waitForTimeout(80);
 const rect=await canvas.evaluate(canvas=>{const c=document.createElement('canvas');c.width=canvas.width;c.height=canvas.height;const ctx=c.getContext('2d');ctx.drawImage(canvas,0,0);const data=ctx.getImageData(0,0,c.width,c.height).data;let left=c.width,right=0,top=c.height,bottom=0;for(let y=0;y<c.height;y++)for(let x=0;x<c.width;x++){const i=(y*c.width+x)*4;if(data[i]>85&&data[i]<170&&Math.abs(data[i]-data[i+1])<15&&Math.abs(data[i]-data[i+2])<15){left=Math.min(left,x);right=Math.max(right,x);top=Math.min(top,y);bottom=Math.max(bottom,y);}}return {left,right,top,bottom};});
 const patch=async()=>canvas.evaluate((canvas,r)=>{const c=document.createElement('canvas');c.width=canvas.width;c.height=canvas.height;const ctx=c.getContext('2d');ctx.drawImage(canvas,0,0);return [...ctx.getImageData(Math.round(r.left+(r.right-r.left)*.12),Math.round(r.top+(r.bottom-r.top)*.12),Math.round((r.right-r.left)*.26),Math.round((r.bottom-r.top)*.26)).data];},rect);
 const before=await patch();assert(before.length>1000);await root.click();await page.waitForTimeout(80);assert.deepEqual(await patch(),before,'Selected dense grid has no internal mesh lines or material tint');
 const exterior=await canvas.evaluate((canvas,{r,dpr})=>{const c=document.createElement('canvas');c.width=canvas.width;c.height=canvas.height;const ctx=c.getContext('2d');ctx.drawImage(canvas,0,0);const d=ctx.getImageData(r.left-4*dpr,Math.round((r.top+r.bottom)/2)-20,4*dpr,40).data;let lit=0;for(let i=0;i<d.length;i+=4)if(d[i]>60&&d[i+1]>60&&d[i+2]>60)lit++;return lit;},{r:rect,dpr});assert(exterior>15,'Muted silhouette visible outside dense geometry at each DPR');
 await page.getByRole('button',{name:'Material',exact:true}).click();const picker=page.getByLabel('Model material controls').getByLabel('Diffuse colour',{exact:true});await picker.fill('#ee3300');await picker.blur();await page.waitForTimeout(100);const after=await patch();assert(after.some((v,i)=>i%4===0&&v>after[i+2]+30),'Material editing stays visible while selected');
 await page.screenshot({path:`work/v080-local/selection-silhouette-dpr${dpr}.png`});assert.deepEqual(errors,[]);await page.close();console.log(`400 adjacent meshes: no interior highlight, live material and outer contour verified at DPR ${dpr}`);
}}finally{await browser.close();}
