import {createRequire} from 'node:module';import assert from 'node:assert/strict';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE||'playwright');const browser=await chromium.launch({channel:'chrome',headless:true});
try {
 const page=await browser.newPage({viewport:{width:1600,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://localhost:3000/');await page.getByText('Manual save only',{exact:true}).waitFor();await page.getByRole('button',{name:'3D',exact:true}).click();await page.getByRole('button',{name:'Import Model…',exact:true}).click();
 const dialog=page.getByRole('dialog');await dialog.locator('input[type=file]').first().setInputFiles({name:'stage.obj',mimeType:'text/plain',buffer:Buffer.from('o Left\nv -2 0 0\nv 0 0 0\nv -1 2 0\nf 1 2 3\no Right\nv 0 0 0\nv 2 0 0\nv 1 2 0\nf 4 5 6')});await dialog.getByRole('button',{name:'Read model',exact:true}).click();await dialog.getByLabel('Source units').selectOption('m');await dialog.getByRole('button',{name:'Import into scene',exact:true}).click();
 const coords=field=>page.getByRole('group',{name:field+' coordinates',exact:true}),x=coords('Position').locator('input').first();const near=async(field,v)=>assert(Math.abs(Number(await field.inputValue())-v)<.005,`${await field.inputValue()} vs ${v}`);
 assert.equal(await page.getByRole('heading',{name:'Model coordinates',exact:true}).count(),0);assert.equal(await x.getAttribute('inputmode'),'decimal');
 await x.fill('2*3-1');await x.press('Enter');await near(x,5);
 const scroll=page.locator('aside[class*="inspector"]').last().locator('[class*="inspectorScroll"]');await x.focus();const top=await scroll.evaluate(e=>e.scrollTop);await x.hover();await page.mouse.wheel(0,-100);await near(x,5.1);assert.equal(await scroll.evaluate(e=>e.scrollTop),top);
 await page.keyboard.down('Shift');await page.mouse.wheel(0,-100);await page.keyboard.up('Shift');await near(x,5.6);assert.equal(await scroll.evaluate(e=>e.scrollTop),top);
 await coords('Position').getByRole('button',{name:'Adjust X',exact:true}).click();await coords('Position').getByRole('button',{name:'Increase X',exact:true}).click({modifiers:['Shift']});await near(x,6.1);await page.keyboard.press('Escape');
 const rz=coords('Rotation').locator('input').nth(2);await rz.fill('360*2+90');await rz.press('Enter');await near(rz,810);
 await page.getByRole('button',{name:'Reset transform',exact:true}).click();await near(x,0);await near(rz,0);
 const view=page.getByRole('region',{name:'3D viewport',exact:true});await view.focus();await page.keyboard.press('F4');await page.keyboard.press('s');await page.keyboard.press('e');await page.waitForTimeout(150);
 const point=await view.locator('canvas').evaluate(canvas=>{const copy=document.createElement('canvas');copy.width=canvas.width;copy.height=canvas.height;const ctx=copy.getContext('2d');ctx.drawImage(canvas,0,0);const data=ctx.getImageData(0,0,copy.width,copy.height).data,pixels=[];for(let y=0;y<copy.height;y++)for(let x=Math.floor(copy.width/2);x<copy.width;x++){const i=(y*copy.width+x)*4;if(data[i]>220&&data[i+1]<40&&data[i+2]<40)pixels.push([x,y]);}const right=Math.max(...pixels.map(p=>p[0])),block=pixels.filter(p=>p[0]>right-10),r=canvas.getBoundingClientRect();return{x:r.x+(right-5)*r.width/copy.width,y:r.y+block.reduce((s,p)=>s+p[1],0)/block.length*r.height/copy.height};});
 await page.mouse.move(point.x,point.y);await page.mouse.down();await page.mouse.move(point.x+45,point.y,{steps:12});await page.waitForTimeout(150);assert(Number(await x.inputValue())>.05,'Coordinates update before the gizmo drag is released');const live=Number(await x.inputValue());await page.mouse.up();await near(x,live);
 await page.keyboard.press('Control+z');const tree=page.getByRole('tree',{name:'Imported models'});await tree.locator('.model-name').first().click();await near(x,0);
 await tree.getByRole('button',{name:/Expand 3D Model/}).click();await tree.getByRole('button',{name:'Expand Group',exact:true}).click();await tree.getByRole('button',{name:'Left',exact:true}).click();await tree.getByRole('button',{name:'Right',exact:true}).click({modifiers:['Control']});await page.waitForFunction(()=>document.querySelector('[aria-label="Position coordinates"] input')?.value==='');assert.equal(await x.inputValue(),'','Different positions show mixed values');
 await x.fill('4/2');await x.press('Enter');await near(x,2);
 await page.screenshot({path:'work/v080-local/shared-coordinates.png'});assert.deepEqual(errors,[]);console.log('Shared model Coordinates: arithmetic, wheel/Shift steps, no panel scrolling, long rotations, reset, live drag before release, Undo and mixed selections passed.');
}finally{await browser.close();}
