import {createRequire} from 'node:module';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {loadRegressionScene} from './browser-fixture.mjs';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE||'playwright');const browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1600,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{window.showSaveFilePicker=undefined;});
try{
 await page.goto('http://localhost:3000/');await page.getByText('Manual save only',{exact:true}).waitFor();await loadRegressionScene(page,'3d');
 const view=page.getByRole('region',{name:'3D viewport',exact:true});await view.focus();await page.keyboard.press('Control+a');await page.keyboard.press('F4');await page.getByRole('button',{name:'Material',exact:true}).click();
 const panel=page.getByLabel('Model material controls',{exact:true});assert(await panel.getByText('Extrusion only — LED display faces retain their content.').count());
 const capture=async()=>{await page.waitForTimeout(120);return view.locator('canvas').first().evaluate(c=>c.toDataURL());};const before=await capture();
 await panel.getByLabel('Diffuse colour',{exact:true}).fill('#ff4400');await panel.getByRole('slider',{name:'Metallic',exact:true}).focus();await page.keyboard.press('End');await panel.getByRole('slider',{name:'Roughness',exact:true}).focus();await page.keyboard.press('Home');
 assert.equal(await capture(),before,'front LED faces and background stay pixel-identical');
 const save=async()=>{await page.getByRole('button',{name:'File',exact:true}).click();const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Save As…',exact:true}).click();return fs.readFile(await (await pending).path());};const bytes=await save(),project=JSON.parse(bytes);assert.equal(project.version,4);const values=Object.values(project.simulation.bodyAppearances);assert.equal(values.length,6);assert(values.every(v=>v.material.color==='#ff4400'&&v.material.metallic===1&&v.material.roughness===0));
 await view.focus();await page.keyboard.press('F1');const surface=page.locator('[aria-label="Perspective viewport"]');const b=await surface.boundingBox();await page.mouse.move(b.x+b.width*.12,b.y+b.height*.15);await page.mouse.down();await page.mouse.move(b.x+b.width*.65,b.y+b.height*.15,{steps:12});await page.mouse.up();await page.screenshot({path:'work/v080-local/led-extrusion-material.png'});
 await page.getByRole('button',{name:'Export',exact:true}).click();const pending=page.waitForEvent('download');await page.getByRole('button',{name:'GLB · Universal binary',exact:true}).click();const glb=await fs.readFile(await (await pending).path());const json=JSON.parse(glb.subarray(20,20+glb.readUInt32LE(12)).toString());assert(json.materials.some(m=>m.name.startsWith('Stage_ff4400')&&m.pbrMetallicRoughness.metallicFactor===1));assert(json.materials.some(m=>m.name==='LED_Surface'&&m.pbrMetallicRoughness.baseColorTexture),'LED texture retained in export');
 await page.locator('input[accept*=".lo2s"]').first().setInputFiles({name:'bodies.lo2s',mimeType:'application/json',buffer:bytes});await view.focus();await page.keyboard.press('Control+a');await page.getByRole('button',{name:'Material',exact:true}).click();assert.equal(await panel.getByLabel('Diffuse colour',{exact:true}).inputValue(),'#ff4400');
 await panel.getByLabel('Material inheritance').selectOption('inherit');assert.equal(await panel.getByLabel('Diffuse colour',{exact:true}).inputValue(),'#252a2d');
 await page.getByRole('button',{name:/^Undo/}).click();await view.focus();await page.keyboard.press('Control+a');assert.equal(await panel.getByLabel('Diffuse colour',{exact:true}).inputValue(),'#ff4400');
 await panel.getByLabel('Material inheritance').selectOption('inherit');await view.focus();await page.keyboard.press('Control+g');
 await panel.getByLabel('Diffuse colour',{exact:true}).fill('#33aaff');await panel.getByLabel('Diffuse colour',{exact:true}).blur();
 const grouped=JSON.parse(await save());assert.equal(grouped.simulation.groups.length,1);assert.equal(grouped.simulation.bodyAppearances[grouped.simulation.groups[0].id].material.color,'#33aaff');assert.equal(Object.keys(grouped.simulation.bodyAppearances).length,1,'group override stays inherited instead of copying onto every child');
 assert.equal(errors.length,0,errors.join('\n'));console.log('LED extrusion: front pixel preservation, multi-selection, material export, save/reopen, inheritance and Undo passed.');
}finally{await browser.close();}
