import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const { chromium } = createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const url = process.env.OPTICMESH_TEST_URL || 'http://127.0.0.1:3090/';
try {
  const page = await browser.newPage({ viewport: { width: 1920, height: 1080 } }), errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(url);
  const button = name => page.getByRole('button', { name, exact: true });
  await button('File').click(); await button('Open Demo').click(); await button('Continue without saving').click();
  await button('Import Model…').click();
  const dialog = page.getByRole('dialog', { name: 'Import 3D model' });
  await dialog.locator('input[type=file]').first().setInputFiles({ name: 'Stage.obj', mimeType: 'text/plain', buffer: Buffer.from('o Platform\nv -5 0 -3\nv 5 0 -3\nv 5 0 3\nv -5 0 3\nf 1 2 3 4\n') });
  await dialog.getByRole('button', { name: 'Read model', exact: true }).click();
  await dialog.locator('.model-preview canvas').waitFor();
  await dialog.getByLabel('Source units').selectOption('m');
  await dialog.getByRole('button', { name: 'Import into scene', exact: true }).click(); await dialog.waitFor({ state: 'detached' });
  await page.evaluate(() => { window.originalViewport = document.querySelector('[aria-label="3D viewport"] canvas'); });
  await button('Plots').click(); await page.getByLabel('Project title', { exact: true }).fill('Sample production');
  const footerNote = page.getByRole('textbox', { name: 'Footer note', exact: true });
  await footerNote.fill(''); await footerNote.pressSequentially('First second'); await footerNote.press('Enter'); await footerNote.press('Enter'); await footerNote.pressSequentially('Third fourth');
  assert.equal(await footerNote.inputValue(), 'First second\n\nThird fourth', 'Space-to-pan must not intercept textarea typing');
  const beforeExpansion = await page.locator('.plots-main').boundingBox();
  await footerNote.evaluate(el => { el.style.height = '450px'; });
  await footerNote.scrollIntoViewIfNeeded();
  const afterExpansion = await page.locator('.plots-main').boundingBox();
  assert.deepEqual(afterExpansion, beforeExpansion, 'Expanding the footer must not move or resize the page workspace');
  for (const selector of ['.plots-tools', '.plots-inspector', '.plots-viewport', '.plots-tools textarea']) {
    const style = await page.locator(selector).first().evaluate(el => ({ width: getComputedStyle(el).scrollbarWidth, colour: getComputedStyle(el).scrollbarColor, scheme: getComputedStyle(el).colorScheme, overflowX: el.scrollWidth > el.clientWidth }));
    assert.equal(style.width, 'thin'); assert.equal(style.colour, 'rgb(69, 75, 78) rgba(0, 0, 0, 0)'); assert.equal(style.scheme, 'dark');
    if (selector !== '.plots-viewport') assert.equal(style.overflowX, false, `${selector} should not overflow horizontally`);
  }
  await page.screenshot({ path: 'work/v090-local/footer-scrollbar.png' });
  await footerNote.evaluate(el => { el.style.height = ''; });

  await button('03 Stage views').click(); await page.waitForFunction(() => document.querySelectorAll('.plots-paper image[data-view-id]').length === 4);
  assert.equal(await page.locator('.plots-paper image').count(), 4);
  await button('3D').click(); assert.equal(await page.evaluate(() => window.originalViewport === document.querySelector('[aria-label="3D viewport"] canvas')), true, 'Editor renderer is retained'); await button('Plots').click();
  await button('01 Input mapping').click(); const paper = page.locator('.plots-paper>svg');
  await page.screenshot({ path: 'work/v090-local/map-coordinates.png' });
  const mapText = await paper.textContent(); assert.ok(mapText.includes('Input X:')); assert.ok(mapText.includes('Y:'));
  await button('02 Output mapping').click(); assert.ok((await paper.textContent()).includes('Output X:')); await button('01 Input mapping').click();
  const markup = await paper.evaluate(n => n.outerHTML); await page.locator('.plots-paper').click({ position: { x: 250, y: 250 } }); assert.equal(await paper.evaluate(n => n.outerHTML), markup, 'Print preview is read-only');
  await page.locator('.plots-inspector').getByRole('button', { name: 'Input map', exact: true }).click();
  await page.getByLabel('Width (mm)', { exact: true }).fill('380'); await page.getByLabel('Sheet title', { exact: true }).fill('Input plan');
  await page.getByLabel('Template name').fill('Regression template'); await button('Save template to library').click();
  const template = await page.evaluate(() => JSON.parse(localStorage.getItem('opticmesh.plot-templates.v1'))[0]); assert.equal(template.document.sheets[0].frames[0].w, 380); assert.equal(template.document.projectTitle, '');
  for (const width of [1280, 1600, 1920]) { await page.setViewportSize({ width, height: 1080 }); const dimensions = await paper.evaluate(n => [n.width.baseVal.value, n.height.baseVal.value]); assert.ok(Math.abs(dimensions[0] / dimensions[1] - 420 / 297) < 0.00001); }
  await page.evaluate(() => { window.lo2sDesktop = { saveProject: async (name, bytes) => { window.savedPlotProject = JSON.parse(new TextDecoder().decode(bytes)); return { ok: true, path: 'C:/Example/Sample production.lo2s' }; } }; });
  await button('File').click(); await button('Save As…').click(); await page.waitForFunction(() => !!window.savedPlotProject);
  const saved = await page.evaluate(() => window.savedPlotProject); assert.equal(saved.technicalPlots.projectTitle, 'Sample production'); assert.equal(saved.technicalPlots.sheets[0].title, 'Input plan'); assert.ok(saved.simulation.models.length);
  const restored = await browser.newPage(); restored.on('pageerror', e => errors.push(e.message));
  await restored.addInitScript(content => { window.lo2sDesktop = { onResolumeXmlUpdated: () => () => {}, onResolumeLinkError: () => () => {}, loadStartupProject: async () => ({ ok: true, restored: true, content }), autosaveProject: async () => ({ ok: true }) }; }, JSON.stringify(saved));
  await restored.goto(url); await restored.locator('.technical-plots').waitFor();
  assert.equal(await restored.getByLabel('Project title', { exact: true }).inputValue(), 'Sample production'); assert.equal(await restored.getByLabel('Sheet title', { exact: true }).inputValue(), 'Input plan');

  // Only the edited camera frame should be regenerated.
  await button('03 Stage views').click();
  await page.waitForFunction(() => document.querySelectorAll('.plots-paper image[data-view-id]').length === 4);
  await page.evaluate(() => { window.plotContexts = 0; const getContext = HTMLCanvasElement.prototype.getContext; HTMLCanvasElement.prototype.getContext = function(type, ...args) { if (type.startsWith('webgl')) window.plotContexts++; return getContext.call(this, type, ...args); }; });
  const beforeViews = await page.locator('.plots-paper image[data-view-id]').evaluateAll(nodes => nodes.map(n => n.getAttribute('href')));
  await page.locator('.plots-inspector').getByRole('button', { name: 'Front', exact: true }).click();
  await page.getByLabel('Camera view', { exact: true }).selectOption('left');
  await page.waitForFunction(old => document.querySelector('.plots-paper image[data-view-id]')?.getAttribute('href') !== old, beforeViews[0]);
  assert.equal(await page.getByLabel('Title', { exact: true }).inputValue(), 'Left');
  const afterViews = await page.locator('.plots-paper image[data-view-id]').evaluateAll(nodes => nodes.map(n => n.getAttribute('href')));
  assert.deepEqual(afterViews.slice(1), beforeViews.slice(1));
  await page.evaluate(() => { window.plotContexts = 0; });
  assert.equal(await page.getByText('Use camera view title', { exact: true }).count(), 0);
  assert.equal(await page.getByText('Cancel view update', { exact: true }).count(), 0);
  await page.getByLabel('Title', { exact: true }).fill('Custom camera');
  await page.getByLabel('Camera view', { exact: true }).selectOption('right');
  assert.equal(await page.getByLabel('Title', { exact: true }).inputValue(), 'Custom camera');
  await page.waitForFunction(old => document.querySelector('.plots-paper image[data-view-id]')?.getAttribute('href') !== old, afterViews[0]);
  assert.equal(await page.evaluate(() => window.plotContexts), 0, 'Camera change reuses capture renderer');
  await page.getByLabel('View zoom', { exact: true }).fill('100*2'); await page.getByLabel('View zoom', { exact: true }).press('Enter');
  assert.equal(await page.getByLabel('View zoom', { exact: true }).inputValue(), '200');
  await page.getByLabel('View pan X', { exact: true }).press('Shift+ArrowUp');
  assert.equal(await page.getByLabel('View pan X', { exact: true }).inputValue(), '10');
  await page.getByLabel('View pan Y', { exact: true }).press('Shift+ArrowDown');
  await page.getByLabel('Camera view', { exact: true }).selectOption('top');
  assert.equal(await page.getByLabel('View zoom', { exact: true }).inputValue(), '100');
  assert.equal(await page.getByLabel('View pan X', { exact: true }).inputValue(), '0');
  assert.equal(await page.getByLabel('View pan Y', { exact: true }).inputValue(), '0');
  assert.equal(await page.getByLabel('Title', { exact: true }).inputValue(), 'Custom camera');
  await page.locator('.plots-inspector').getByRole('button', { name: 'Custom camera', exact: true }).click();
  await page.keyboard.press('Control+z');
  assert.equal(await page.getByLabel('Camera view', { exact: true }).inputValue(), 'right');
  assert.equal(await page.getByLabel('View zoom', { exact: true }).inputValue(), '200');
  assert.equal(await page.getByLabel('View pan X', { exact: true }).inputValue(), '10');
  assert.equal(await page.getByLabel('View pan Y', { exact: true }).inputValue(), '-10');
  await page.keyboard.press('Control+y');
  await button('Adjust view framing').click();
  const cameraSurface = page.getByLabel('Frame camera controls'); const cameraBox = await cameraSurface.boundingBox();
  await page.mouse.move(cameraBox.x + cameraBox.width / 2, cameraBox.y + cameraBox.height / 2);
  const scrollBefore = await page.locator('.plots-viewport').evaluate(n => n.scrollTop);
  const footerBefore = await page.locator('.plots-status').boundingBox();
  await page.mouse.wheel(0, -120);
  await page.waitForFunction(() => document.querySelector('.plots-compose img').style.transform.includes('1.1'));
  assert.deepEqual(await page.locator('.plots-status').boundingBox(), footerBefore, 'Footer never changes layout during capture');
  await page.waitForFunction(() => Number(document.querySelector('input[aria-label="View zoom"]').value) > 100);
  assert.equal(await page.locator('.plots-viewport').evaluate(n => n.scrollTop), scrollBefore);
  await page.mouse.down(); await page.mouse.move(cameraBox.x + cameraBox.width / 2 + 20, cameraBox.y + cameraBox.height / 2 + 10, { steps: 3 }); await page.mouse.up();
  assert.ok(Number(await page.getByLabel('View pan X', { exact: true }).inputValue()) < 0);
  await page.mouse.wheel(0, -120);
  await page.getByLabel('Camera view', { exact: true }).selectOption('right');
  await page.waitForTimeout(350); // Let the previous wheel debounce expire: it must not restore old framing.
  assert.equal(await page.getByLabel('View zoom', { exact: true }).inputValue(), '100');
  assert.equal(await page.getByLabel('View pan X', { exact: true }).inputValue(), '0');
  assert.equal(await page.getByLabel('View pan Y', { exact: true }).inputValue(), '0');
  await button('Finish framing').click(); await button('Fit view').click();
  // Blank sheet: frame is placed under the cursor only after a click.
  await page.getByLabel('Add sheet', { exact: true }).selectOption('blank');
  await page.getByLabel('Add frame', { exact: true }).selectOption('text');
  assert.equal(await page.locator('.plots-paper>svg>g').count(), 0);
  const bounds = await page.locator('.plots-paper').boundingBox();
  await page.mouse.move(bounds.x + bounds.width * 60 / 420, bounds.y + bounds.height * 80 / 297);
  assert.equal(await page.locator('.plots-ghost').count(), 1);
  await page.mouse.click(bounds.x + bounds.width * 60 / 420, bounds.y + bounds.height * 80 / 297);
  assert.equal(await page.getByLabel('X (mm)', { exact: true }).inputValue(), '60');
  assert.equal(await page.getByLabel('Y (mm)', { exact: true }).inputValue(), '80');
  assert.equal(await page.getByLabel('Width (mm)', { exact: true }).inputValue(), '180');
  await page.getByLabel('Width (mm)', { exact: true }).fill('180/2'); await page.getByLabel('Width (mm)', { exact: true }).press('Enter');
  assert.equal(await page.getByLabel('Width (mm)', { exact: true }).inputValue(), '90');
  await button('Adjust Width (mm)').click();
  await button('Increase Width (mm)').click({ modifiers: ['Shift'] });
  assert.equal(await page.getByLabel('Width (mm)', { exact: true }).inputValue(), '100');
  await page.getByLabel('Sheet title', { exact: true }).click();
  const resize = await page.getByRole('button', { name: 'Resize Delivery notes', exact: true }).boundingBox();
  await page.mouse.move(resize.x + resize.width / 2, resize.y + resize.height / 2); await page.mouse.down();
  await page.mouse.move(resize.x + resize.width / 2 + bounds.width * 17 / 420, resize.y + resize.height / 2 + bounds.height * 12 / 297, { steps: 4 });
  assert.equal(await page.getByLabel('Width (mm)', { exact: true }).inputValue(), '115', 'Live resize width snaps to 5mm');
  assert.equal(await page.getByLabel('Height (mm)', { exact: true }).inputValue(), '110');
  await page.mouse.up();
  assert.equal(await page.getByLabel('X (mm)', { exact: true }).inputValue(), '60');
  assert.equal(await page.getByLabel('Y (mm)', { exact: true }).inputValue(), '80');
  await page.getByLabel('Add frame', { exact: true }).selectOption('view');
  await page.mouse.move(bounds.x + bounds.width * 200 / 420, bounds.y + bounds.height * 81 / 297);
  assert.ok((await page.locator('.plots-guides').textContent()).includes('25 mm'));
  await page.screenshot({ path: 'work/v090-local/alignment-guides.png' });
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('.plots-placement').count(), 0);
  // Copies preserve settings, remain independent, and create one undo step.
  await page.getByLabel('Frame text size', { exact: true }).fill('11'); await page.getByLabel('Frame text size', { exact: true }).press('Enter');
  await page.getByLabel('Text', { exact: true }).fill('Reusable frame content');
  await page.locator('.plots-inspector').getByRole('button', { name: 'Delivery notes', exact: true }).click();
  await page.keyboard.press('Control+d');
  assert.equal(await page.locator('.plots-frame-control').count(), 2);
  assert.equal(await page.getByLabel('X (mm)', { exact: true }).inputValue(), '180');
  assert.equal(await page.getByLabel('Width (mm)', { exact: true }).inputValue(), '115');
  assert.equal(await page.getByLabel('Height (mm)', { exact: true }).inputValue(), '110');
  assert.equal(await page.getByLabel('Frame text size', { exact: true }).inputValue(), '11');
  assert.equal(await page.getByLabel('Text', { exact: true }).inputValue(), 'Reusable frame content');
  await page.keyboard.press('Control+z'); assert.equal(await page.locator('.plots-frame-control').count(), 1);
  await page.keyboard.press('Control+y'); assert.equal(await page.locator('.plots-frame-control').count(), 2);
  await page.locator('.plots-inspector').getByRole('button', { name: 'Delivery notes', exact: true }).last().click();
  await page.getByLabel('Text', { exact: true }).fill('Independent copy');
  await page.locator('.plots-inspector').getByRole('button', { name: 'Delivery notes', exact: true }).first().click();
  assert.equal(await page.getByLabel('Text', { exact: true }).inputValue(), 'Reusable frame content');
  const originalFrame = await page.getByRole('button', { name: 'Move Delivery notes', exact: true }).first().boundingBox();
  await page.keyboard.down('Alt'); await page.mouse.move(originalFrame.x + 30, originalFrame.y + 30); await page.mouse.down();
  await page.mouse.move(originalFrame.x + 30, originalFrame.y + 30 - bounds.height * 49 / 297, { steps: 5 });
  await page.mouse.up(); await page.keyboard.up('Alt');
  assert.equal(await page.locator('.plots-frame-control').count(), 3);
  assert.equal(await page.getByLabel('Y (mm)', { exact: true }).inputValue(), '30');
  assert.equal(await page.getByLabel('Text', { exact: true }).inputValue(), 'Reusable frame content');
  await page.locator('.plots-inspector').getByRole('button', { name: 'Delivery notes', exact: true }).first().click();
  assert.equal(await page.getByLabel('Y (mm)', { exact: true }).inputValue(), '80', 'Alt-drag leaves original unchanged');
  await page.getByLabel('Title', { exact: true }).focus(); await page.keyboard.press('Control+d');
  assert.equal(await page.locator('.plots-frame-control').count(), 3, 'Shortcut ignores text editing');
  await page.screenshot({ path: 'work/v090-local/frame-copies.png' });
  // Reorder with the same before/after drop interaction as hierarchy rows.
  const rows = page.locator('.plots-sheet-list>button');
  const last = await rows.last().boundingBox();
  await rows.first().dragTo(rows.last(), { targetPosition: { x: 40, y: last.height - 2 } });
  assert.match(await rows.last().innerText(), /Input plan/);
  // Screen details use actual configured 500mm / 128px cabinets, not an arbitrary grid.
  await page.getByLabel('Add sheet', { exact: true }).selectOption('pattern');
  await page.locator('.plots-inspector').getByRole('button', { name: 'Screen detail', exact: true }).click();
  const grid = page.locator('.plots-paper pattern');
  assert.equal(await grid.count(), 1);
  const caption = await page.locator('.plots-paper').innerText();
  assert.ok(caption.includes('500 × 500 mm'));
  assert.ok(caption.includes('128 × 128 px'));
  await button('Duplicate frame').click();
  assert.equal(await page.locator('.plots-placement').count(), 1, 'Full-size frame offers cursor placement when no adjacent space is free');
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('.plots-frame-control').count(), 1, 'Cancelling placement creates no copy');
  await page.getByLabel('Width (mm)', { exact: true }).fill('180'); await page.getByLabel('Width (mm)', { exact: true }).press('Enter');
  await page.getByLabel('Height (mm)', { exact: true }).fill('100'); await page.getByLabel('Height (mm)', { exact: true }).press('Enter');
  await button('Duplicate frame').click();
  assert.equal(await page.locator('.plots-frame-control').count(), 2);
  assert.equal(await page.getByLabel('Screen slice', { exact: true }).inputValue(), '0');
  await page.getByLabel('Screen slice', { exact: true }).selectOption('1');
  await page.locator('.plots-inspector').getByRole('button', { name: 'Screen detail', exact: true }).first().click();
  assert.equal(await page.getByLabel('Screen slice', { exact: true }).inputValue(), '0', 'Each copied detail can select a different slice');
  const patternIds = await page.locator('.plots-paper pattern').evaluateAll(nodes => nodes.map(n => n.id));
  assert.equal(new Set(patternIds).size, 2, 'Copies have independent SVG identifiers');
  await page.screenshot({ path: 'work/v090-local/updated-pattern.png' });
  // Native calls are intercepted here: no physical printer is used by this test.
  await page.evaluate(() => Object.assign(window.lo2sDesktop, {
    getPlotPrinters: async () => ({ printers: [{ name: 'QA printer', isDefault: true }] }),
    printTechnicalPlots: async payload => { window.plotPrintPayload = payload; return { path: 'test.pdf' }; }
  }));
  await page.waitForFunction(() => ![...document.querySelectorAll('.plots-toolbar button')].find(n => n.textContent === 'Refresh views')?.disabled);
  await page.locator('[aria-controls=toolbar-menu-export]').click(); await button('Export A3 PDF…').click();
  await page.waitForFunction(() => !!window.plotPrintPayload);
  const payload = await page.evaluate(() => window.plotPrintPayload);
  assert.equal(payload.print, false); assert.ok(payload.pages.every(p => p.includes('width="420mm"') && p.includes('height="297mm"')));
  fs.writeFileSync('work/v090-local/pages.json', JSON.stringify(payload.pages));
  await page.locator('[aria-controls=toolbar-menu-export]').click(); await button('Print…').click();
  const print = page.getByRole('dialog', { name: 'Print technical plots' }); await print.waitFor();
  assert.equal(await print.locator('svg[role=img]').count(), 1);
  await print.getByRole('button', { name: 'Next preview page' }).click();
  await print.getByLabel('Copies', { exact: true }).fill('1+1'); await print.getByLabel('Copies', { exact: true }).press('Enter');
  await print.getByLabel('Pages', { exact: true }).selectOption('current');
  await page.screenshot({ path: 'work/v090-local/updated-print-preview.png' });
  await print.getByRole('button', { name: 'Print', exact: true }).click();
  await print.waitFor({ state: 'detached' });
  const printed = await page.evaluate(() => window.plotPrintPayload);
  assert.equal(printed.deviceName, 'QA printer'); assert.equal(printed.copies, 2); assert.equal(printed.pages.length, 1);
  assert.deepEqual(errors, []); console.log('Plots: model captures, camera refresh isolation, retained viewport, static A3 paper, arithmetic/Shift controls, cursor placement, sheet dragging, panel grid, PDF dispatch, print preview and project restoration passed.');
} finally { await browser.close(); }
