import {createRequire} from 'node:module';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import * as THREE from 'three';import {encodeArray} from '../app/model-data.ts';import {transformMatrix} from '../app/group-transforms.ts';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE||'playwright');const browser=await chromium.launch({channel:'chrome',headless:true});
const rawXml=await fs.readFile(new URL('./fixtures/six-screen-regression.xml',import.meta.url),'utf8');
const targetMatrix=new THREE.Matrix4().compose(new THREE.Vector3(8,3,0),new THREE.Quaternion().setFromEuler(new THREE.Euler(.15,.3,.35)),new THREE.Vector3(1,1,1)).toArray();
const model={id:'reference',name:'Reference',format:'obj',hierarchy:true,triangles:2,warnings:[],geometries:{g:{position:encodeArray(new Float32Array([-3,-2,0,3,-2,0,3,2,0,-3,-2,0,3,2,0,-3,2,0]))}},nodes:[{id:'target',parent:null,name:'Target screen',matrix:targetMatrix,geometry:'g',visible:true,locked:true}]};
const original={position:[-8,0,0],rotation:[.1,-.2,.25],scale:[1.2,.8,1.3]};
const fixture={format:'opticmesh-project',version:4,config:{project:'Transfer test',pixelPitchMm:3.9,cabinetWidth:500},rawXml,workspaceMode:'simulation',simulation:{models:[model],transforms:{'demo-centre':original},pivot:'bottom-center',depthM:.1,source:'pattern',floorVisible:false,gridVisible:false,visibility:Object.fromEntries(['demo-left','demo-right','demo-header','demo-floor-left','demo-floor-right'].map(id=>[id,false]))}};
try{
 const page=await browser.newPage({viewport:{width:1800,height:1050}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{window.showSaveFilePicker=undefined;});await page.goto('http://localhost:3000/');await page.getByText('Manual save only',{exact:true}).waitFor();
 const load=async()=>{await page.locator('input[accept=".lo2s,application/x-opticmesh-project,.json,application/json"]').setInputFiles({name:'transfer.lo2s',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(fixture))});await page.getByText('Project loaded: transfer.lo2s',{exact:true}).waitFor();};
 const save=async()=>{await page.getByRole('button',{name:'File',exact:true}).click();const event=page.waitForEvent('download');await page.getByRole('button',{name:'Save As…',exact:true}).click();return JSON.parse(await fs.readFile(await (await event).path(),'utf8'));};
 await load();const view=page.getByRole('region',{name:'3D viewport',exact:true}),button=page.getByRole('button',{name:'Transfer',exact:true});assert(await button.isDisabled());
 for(const shortcut of ['F4','F5']){
  if(shortcut==='F5')await load();
  await view.focus();await page.keyboard.press(shortcut);await page.keyboard.press('f');await page.getByRole('button',{name:'Select Centre Wall',exact:true}).click();assert(!(await button.isDisabled()));
  await button.click();assert.equal(await button.getAttribute('aria-pressed'),'true');await page.keyboard.press('Escape');assert.equal(await button.getAttribute('aria-pressed'),'false');await button.click();
  const pane=view.locator('[aria-label="Front viewport"]');await page.waitForTimeout(150);const bounds=await pane.boundingBox();
  const point=await view.locator('canvas').evaluate((canvas,b)=>{const copy=document.createElement('canvas');copy.width=canvas.width;copy.height=canvas.height;const ctx=copy.getContext('2d');ctx.drawImage(canvas,0,0);const d=ctx.getImageData(0,0,copy.width,copy.height).data,r=canvas.getBoundingClientRect(),ratio=canvas.width/r.width;let sx=0,sy=0,n=0;for(let y=Math.ceil((b.y-r.y)*ratio);y<(b.y+b.height-r.y)*ratio;y++)for(let x=Math.ceil((b.x-r.x)*ratio);x<(b.x+b.width-r.x)*ratio;x++){const i=(y*copy.width+x)*4;if(d[i]>65&&d[i]<180&&Math.abs(d[i]-d[i+1])<20&&Math.abs(d[i]-d[i+2])<20){sx+=x;sy+=y;n++;}}if(n<100)throw new Error('No target pixels');return{x:r.x+sx/n/ratio,y:r.y+sy/n/ratio};},bounds);
  await page.screenshot({path:'work/v080-local/transfer-'+shortcut+'.png'});await page.mouse.click(point.x,point.y);await page.waitForFunction(()=>!document.querySelector('.three-view[data-transfer-active]'));
  const result=await save(),t=result.simulation.transforms['demo-centre'];const q=new THREE.Quaternion().setFromEuler(new THREE.Euler(...t.rotation)),expectedQ=new THREE.Quaternion();new THREE.Matrix4().fromArray(targetMatrix).decompose(new THREE.Vector3(),expectedQ,new THREE.Vector3());assert(q.angleTo(expectedQ)<1e-6);for(let i=0;i<3;i++)assert(Math.abs(t.scale[i]-original.scale[i])<1e-6);assert.equal(result.simulation.pivot,'bottom-center');assert.deepEqual(result.simulation.models[0].nodes[0].matrix,targetMatrix);
  const height=1320*(500/128)/1000;const center=new THREE.Vector3(0,height/2,-.05).multiply(new THREE.Vector3(...t.scale)).applyQuaternion(q).add(new THREE.Vector3(...t.position));assert(center.distanceTo(new THREE.Vector3(8,3,0))<1e-5,center.toArray().join(','));
  await view.focus();await page.keyboard.press('Control+z');const undone=await save();assert.deepEqual(undone.simulation.transforms['demo-centre'],original);await view.focus();await page.keyboard.press('Control+Shift+z');const redone=await save();assert.deepEqual(redone.simulation.transforms['demo-centre'],t);
 }
 const sourceMatrix=new THREE.Matrix4().compose(new THREE.Vector3(-8,2,0),new THREE.Quaternion().setFromEuler(new THREE.Euler(...original.rotation)),new THREE.Vector3(...original.scale)).toArray();
 const sourceModel={...model,id:'source-model',nodes:[{id:'source-node',parent:null,name:'Source mesh',matrix:sourceMatrix,geometry:'g',visible:true,locked:false,pivot:[1,-2,.5],pivotMode:'custom'}]};
 const pickTarget=async()=>{await page.waitForTimeout(120);const bounds=await view.locator('[aria-label="Front viewport"]').boundingBox();const point=await view.locator('canvas').evaluate((canvas,b)=>{const copy=document.createElement('canvas');copy.width=canvas.width;copy.height=canvas.height;const ctx=copy.getContext('2d');ctx.drawImage(canvas,0,0);const d=ctx.getImageData(0,0,copy.width,copy.height).data,r=canvas.getBoundingClientRect(),ratio=canvas.width/r.width;let sx=0,sy=0,n=0;for(let y=Math.ceil((b.y-r.y)*ratio);y<(b.y+b.height-r.y)*ratio;y++)for(let x=Math.ceil((b.x+b.width/2-r.x)*ratio);x<(b.x+b.width-r.x)*ratio;x++){const i=(y*copy.width+x)*4;if(d[i]>65&&d[i]<180&&Math.abs(d[i]-d[i+1])<20&&Math.abs(d[i]-d[i+2])<20){sx+=x;sy+=y;n++;}}if(n<100)throw new Error('No target pixels');return{x:r.x+sx/n/ratio,y:r.y+sy/n/ratio};},bounds);await page.mouse.click(point.x,point.y);await page.waitForFunction(()=>!document.querySelector('.three-view[data-transfer-active]'));};
 for(const group of [false,true]){
  fixture.simulation.models=[model,structuredClone(sourceModel)];fixture.simulation.visibility['demo-centre']=!group?false:true;
  if(group){fixture.simulation.models[1].nodes[0].sceneGroupId='assembly';fixture.simulation.groups=[{id:'assembly',name:'Assembly',parentId:null,sliceIds:['demo-centre'],expanded:true,visible:true,locked:false,transform:{position:[0,0,0],rotation:[0,0,0],scale:[1,1,1]}}];}
  await load();await view.focus();await page.keyboard.press('F4');await page.keyboard.press('f');
  if(group)await page.locator('.hierarchy-group-name > span[title="Assembly"]').click();else await page.getByRole('button',{name:'Source mesh',exact:true}).click();
  assert(!(await button.isDisabled()));await button.click();await pickTarget();const result=await save(),m=result.simulation.models[1].nodes[0];assert.deepEqual(m.pivot,[1,-2,.5]);assert.deepEqual(result.simulation.models[0].nodes[0].matrix,targetMatrix);
  if(!group){const after=new THREE.Matrix4().fromArray(m.matrix),position=new THREE.Vector3(),q=new THREE.Quaternion(),scale=new THREE.Vector3();after.decompose(position,q,scale);assert(position.distanceTo(new THREE.Vector3(8,3,0))<1e-5);assert(scale.distanceTo(new THREE.Vector3(...original.scale))<1e-5);}
  else {
    const bounds=new THREE.Box3(new THREE.Vector3(-3,-2,0),new THREE.Vector3(3,2,0)).applyMatrix4(new THREE.Matrix4().fromArray(sourceMatrix));const pitch=(500/128)/1000;
    bounds.union(new THREE.Box3(new THREE.Vector3(-1760*pitch/2,0,-.1),new THREE.Vector3(1760*pitch/2,1320*pitch,0)).applyMatrix4(transformMatrix(original)));
    const groupMatrix=transformMatrix(result.simulation.groups[0].transform);assert(bounds.getCenter(new THREE.Vector3()).applyMatrix4(groupMatrix).distanceTo(new THREE.Vector3(8,3,0))<1e-5);assert.deepEqual(result.simulation.transforms['demo-centre'],original);
    const expected=groupMatrix.clone().multiply(new THREE.Matrix4().fromArray(sourceMatrix));assert(expected.elements.every((v,i)=>Math.abs(v-m.matrix[i])<1e-6));
  }
  await view.focus();await page.keyboard.press('Control+z');const undone=await save();assert.deepEqual(undone.simulation.models[1].nodes[0].matrix,sourceMatrix);
 }
 assert.deepEqual(errors,[]);console.log('Transfer: pivot compensation, orientation, preserved scale/target/mapping, cancel, selection, Undo/Redo and All Views passed.');
}finally{await browser.close();}
