import { useEffect, useRef, useState, type ReactNode } from 'react';
import PlotNumberField from './plot-number-field';

type Printer = { name: string; displayName?: string; isDefault?: boolean };
export default function PlotPrintDialog({ pages, busy, onClose, onPrint, onPdf, onNotice }: { pages: ReactNode[]; busy: boolean; onClose: () => void; onPrint: (device: string, copies: number, page?: number) => void; onPdf: () => void; onNotice: (message: string) => void }) {
  const root = useRef<HTMLDialogElement>(null), [page, setPage] = useState(0), [printers, setPrinters] = useState<Printer[]>([]), [device, setDevice] = useState(''), [copies, setCopies] = useState(1), [range, setRange] = useState('all'), [error, setError] = useState('');
  useEffect(() => {
    const previous = document.activeElement as HTMLElement | null; const dialog = root.current!; dialog.showModal(); dialog.focus(); let disposed = false;
    const bridge = (window as unknown as { lo2sDesktop?: { getPlotPrinters?: () => Promise<{ printers?: Printer[]; error?: string }> } }).lo2sDesktop;
    const request = bridge?.getPlotPrinters ? bridge.getPlotPrinters() : Promise.resolve({ error: 'Restart the local desktop app to enable printer selection. PDF export is available.', printers: [] });
    request.then(result => { if (disposed) return; setPrinters(result.printers || []); setDevice(result.printers?.find(p => p.isDefault)?.name || result.printers?.[0]?.name || ''); setError(result.error || (!result.printers?.length ? 'No printers found. You can export the sheets to PDF.' : '')); }).catch(() => { if (!disposed) setError('Unable to list printers. You can export the sheets to PDF.'); });
    return () => { disposed = true; dialog.close(); previous?.focus(); };
  }, []);
  return <dialog className="plots-print-dialog" role="dialog" aria-modal="true" aria-label="Print technical plots" tabIndex={-1} ref={root} onCancel={e => { e.preventDefault(); if (!busy) onClose(); }} onKeyDown={e => {
    if (e.key === 'Escape') { e.preventDefault(); e.stopPropagation(); if (!busy) onClose(); }
    if (e.key === 'Tab') { const controls = Array.from(root.current!.querySelectorAll<HTMLElement>('button:not(:disabled),select:not(:disabled),input:not(:disabled)')); const first = controls[0], last = controls.at(-1); if (e.shiftKey && (document.activeElement === first || document.activeElement === root.current)) { e.preventDefault(); last?.focus(); } else if (!e.shiftKey && (document.activeElement === last || document.activeElement === root.current)) { e.preventDefault(); first?.focus(); } }
  }}><header><h2>Print technical plots</h2><button disabled={busy} aria-label="Close print preview" onClick={onClose}>×</button></header><div className="plots-print-body"><aside><h3>PRINT SETTINGS</h3><label>Printer<select aria-label="Printer" value={device} onChange={e => setDevice(e.target.value)} disabled={!printers.length}>{!printers.length && <option value="">No printer available</option>}{printers.map(p => <option key={p.name} value={p.name}>{p.displayName || p.name}</option>)}</select></label><label>Pages<select aria-label="Pages" value={range} onChange={e => setRange(e.target.value)}><option value="all">All sheets</option><option value="current">Current preview sheet</option></select></label><PlotNumberField label="Copies" value={copies} min={1} max={99} onChange={n => setCopies(Math.round(n))}/><p>A3 landscape · 420 × 297 mm</p>{error && <p className="plots-print-error">{error}</p>}</aside><div className="plots-print-view"><div className="plots-print-page">{pages[page]}</div><nav><button disabled={page === 0} aria-label="Previous preview page" onClick={() => setPage(page - 1)}>‹</button><span>Sheet {page + 1} / {pages.length}</span><button disabled={page >= pages.length - 1} aria-label="Next preview page" onClick={() => setPage(page + 1)}>›</button></nav></div></div><footer><button disabled={busy} onClick={onClose}>Cancel</button><button disabled={busy} onClick={onPdf}>Export PDF…</button><button className="active" disabled={busy || !device} onClick={() => { if (!device) return onNotice('Choose a printer.'); onPrint(device, copies, range === 'current' ? page : undefined); }}>Print</button></footer></dialog>;
}
